name: Build and run tests
on: [push, pull_request]
jobs:
  tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: |
        cargo build
    - run: |
        cargo test
