name: Build and run tests
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  tests:
    strategy:
      matrix:
        toolchain: [stable, nightly]
        toolchain-suffix: [unknown-linux-gnu, apple-darwin, pc-windows-msvc, pc-windows-gnu]
        include:
          - toolchain-suffix: unknown-linux-gnu
            os: ubuntu-latest
          - toolchain-suffix: apple-darwin
            os: macos-latest
          - toolchain-suffix: pc-windows-gnu
            os: windows-latest
          - toolchain-suffix: pc-windows-msvc
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.toolchain }}-${{ matrix.toolchain-suffix }}
    - uses: Swatinem/rust-cache@v2
    - run: |
        rustup show
    - uses: actions/checkout@v4
      with:
        submodules: true
    - run: |
        cargo build
    - run: |
        cargo test
    - run: |
        cargo package
