name: Build and run tests
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: |
        cargo build
    - run: |
        cargo test
